version: 2

sources:
  - name: DBT_GSEDA
    database: ANALYTICS
    # schema: YOUR_SCHEMA   # optional but recommended

    tables:
      - name: MY_FIRST_DBT_MODEL
        loaded_at_field: loaded_at

        freshness:
          warn_after:
            count: 1
            period: minute     # minute | hour | day
          error_after:
            count: 9999
            period: day